### PR TITLE
fix: Fix socket.io server not starting properly

### PR DESCRIPTION
**Pull request by jrassa**
Fixes issue introduced in #111

### CODE REVIEW

**Review by brianghig — CHANGES_REQUESTED** [review]
@jrassa Thanks for this change! I have a few other updates I'd like to see in this PR, namely around the express.js middlware initializations that eventually lead to this socket.io update. IMO, we can / should be more explicit about what's being returned from the express.js' init() method that's handled in the server startup callback. I'll send up a commit for that first thing tomorrow morning.

**Comment by jrassa** [comment]
@brianghig Sure.  Let me know what you want done, or feel free to jump in.

**Review by brianghig — APPROVED** [review]
@jrassa I just pushed those changes, and it looks good to me. Thanks for getting this moving!

**Comment by jrassa** [comment]
@brianghig I pushed some additional changes decoupling the initialization of socket.io from express.

**Review by brianghig — APPROVED** [review]

**Pull request merged**
