### PR TITLE
remove unused moment dependency

### PR DESCRIPTION
**Pull request by jrassa**
Explicit uses of moment were removed in #138, but the dependency wasn't removed to give downstream projects time to adjust.

### CODE REVIEW

**Comment by brianghig** [comment]
@jrassa - should we remove this from `package-lock.json` as well? Regenerate that with some of the latest versions and without `moment`?

**Comment by jrassa** [comment]
@brianghig I don't think we can remove moment from `package-lock.json`.  It is still used as a dependency of some other node modules we are using.  I tried deleting and regenerating and it is still included.

**Comment by eacaps** [comment]
Just removing it from `package.json` is okay, but I would recommend either doing `npm uninstall moment` or fully regenerating the package-lock.json any time the dependencies are changed `rm -rf node_modules;npm install`. Either way you will have a new `package-lock.json`(which should never be hand edited). This way the dependency tree will be updated and if moment was not being used elsewhere in the dependency tree it would have gone away..

**Comment by jrassa** [comment]
I just verified that regenerating package-lock.json(with node v14.17), as described above, results in no changes to package-lock.json.

**Review by eacaps — APPROVED** [review]

**Pull request merged**
