### PR TITLE
Feat/typescript

### PR DESCRIPTION
**Pull request by gu**
Throwing up the initial set of work to introduce an intermediate typescript compiler/transpiler into the starter mix. I approached this task with a few use cases, including:

Linting: ✅  - Working well with new NPM scripts
Production build  ✅  - Working well with new NPM scripts
Testing ✅  - Working well with NPM scripts, also introduced a prod:test script to run tests against 'compiled' code
Development ✅  - Working well with npm scripts, including live reloading
Dockerization ✅ 
Debugging ✅ 

I'm completely open to additional considerations and comments, and am in no way emotionally attached to these proposed changes - they just seemed to work so far 🙃 

@brianghig @tzfx Please feel free to propose changes or pull things down to change directly

### CODE REVIEW

**Comment by tzfx** [comment]
Aw sweet

**Comment by jrassa** [comment]
@gu Looks great.  I did a quick test and converted `feedback.service.js` into Typescript.  Worked perfectly.

Debugging appears to work properly if we set `"inlineSourceMap": true` in `tsconfig.json`.

**Comment by gu** [comment]
@jrassa Wow! yeah that seems to have done it. Thanks for the investigation!!

With that, I don't have any additional things I want to investigate for this other than general viability and stability. I'll take the WIP flag off

**Comment by brianghig** [comment]
I'm seeing a few typescript files that will change with the updated `npm run lint:fix` tooling, but everything else LGTM! Nice work @gu  💯  

Approving and merging.

**Review by brianghig — APPROVED** [review]

**Pull request merged**
