### PR TITLE
configurable option to serve static UI

### PR DESCRIPTION
**Pull request by jrassa**

### CODE REVIEW

**Comment by reblace** [comment]
Would this be better as an option to generically serve static content from the dist dir? It's not really specific to the UI, it could just be some content files. Are we setting no cache headers?

**Comment by jrassa** [comment]
Cache headers are being set by default since it is using `express.static`.  I added the ability to configure the cache options.

**Comment by reblace** [comment]
Not to beat a dead horse, but I like how Angular CLI does this. They have an assets property that points to an array of globs or objects. If they're objects, you can specify input and output paths.

```
"assets": [
    "assets",
    "favicon.ico"
]
```

That allows you to provide multiple paths and/or expose things from within a node_modules directory. Though, they actually just copy the content into the dist dir and assume you'll handle exposing it.

As a separate question, what is this for? Is it for production use? Do we want people doing this in production and not running an instance of nginx or apache?

**Comment by jrassa** [comment]
> As a separate question, what is this for? Is it for production use? Do we want people doing this in production and not running an instance of nginx or apache?

Potentially.  The main thought behind it was that it would allow for assembling the static UI code and the rest code into a single deployable unit.  Implementing this wouldn't prevent the use of nginx or apache.  If you don't think we should include this, we can just close this ticket.

**Review by brianghig — APPROVED** [review]

**Comment by brianghig** [comment]
@jrassa still interested in supporting this from the node app?

**Pull request closed without merging**
